### PR TITLE
Feature/sd 578 move saritasa GitHub actions to saritasa nest

### PR DESCRIPTION
**Pull request by AntonZiminSaritasa**
Add `generate-version` action.

https://github.com/AntonZiminSaritasa/saritasa-github-actions/blob/feature/SD-578-move-saritasa-github-actions-to-saritasa-nest/generate-version/README.md

The action package was created in the root dir instead of `.github/actions`.
https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action

### CODE REVIEW

**Comment by dmitry-mightydevops** [comment]
@AntonZiminSaritasa why 729 files? How you expect us to review that?
Have you pushed any built artifacts in the PR?

**Comment by AntonZiminSaritasa** [comment]
node_modiles must be pushed to the repository. That's how JS Actions work.

**Comment by AntonZiminSaritasa** [comment]
An alternative is to build a binary blob using https://github.com/vercel/ncc and push it instead of node_modules. I'll consider it.

>  submission of node_modules dir essentially make this repo a single action repo

No, it'll make node_modules reusable by future actions.

**Comment by dmitry-mightydevops** [comment]
> No, it'll make node_modules reusable by future actions.
how come?

If I have different package.json versions between action A and action B - what would happen?

**Comment by AntonZiminSaritasa** [comment]
You'll have one package.json but different action.yml files.

**Comment by dmitry-mightydevops** [comment]
I don't understand Anton.
1. Action a, need version ==1.0
2. Action b, need version == 2.0 which is breaking changes.

Single package.json will not work in such cases. Again this is OK for a single action repo, which this one is not.

**Comment by AntonZiminSaritasa** [comment]
If you use one repository for multiple actions - use the same versions of packages.
Otherwise, simply put every action into a separate repo.

**Comment by dmitry-mightydevops** [comment]
@roman-mightydevops pls create new repo
```
saritasa-github-actions-getversion
```

@AntonZiminSaritasa  pls open new PR once this repo is up.

This PR is closed.

**Comment by dmitry-mightydevops** [comment]
Closing

**Comment by roman-mightydevops** [comment]
> saritasa-github-actions-getversion



> @roman-mightydevops pls create new repo
> 
> ```
> saritasa-github-actions-getversion
> ```
> 
> @AntonZiminSaritasa pls open new PR once this repo is up.
> 
> This PR is closed.

@AntonZiminSaritasa https://github.com/saritasa-nest/saritasa-github-actions-getversion

**Pull request closed without merging**
